- name: Prep hosts for airgap install method
  block:
    - name: Make /opt/rke2/ directory
      ansible.builtin.file:
        path: /opt/rke2/
        state: directory
    
    - ansible.builtin.debug:
        msg: "Coping dependencies to opt/rke2/ on remote host. Approximately 1GB to transfer, please be patient"
    
    - name: Copy dependencies to remote host
      ansible.builtin.copy:
        src: ../dependencies/
        dest: /opt/rke2
        owner: root
        group: root
  when: AIRGAP_INSTALL_METHOD == true
  