- hosts: all
  become: yes
  tasks:
    - import_role:
        name: common
- hosts: cluster_master
  become: yes
  tasks:
    - import_role:
        name: masters
- hosts: cluster_workers
  become: yes
  tasks: 
    - import_role:
        name: workers